on:
  push:
    branches:
      - '*'
  
jobs:
  test-backend:
    runs-on: ubuntu-latest
    env:
      DB_HOST: db
      REDIS_HOST: redis
      RABBITMQ_HOST: rabbitmq
      FRONTEND_HOST: http://localhost:5173
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      POSTGRES_DB: ${{ secrets.DB_NAME }}
      RABBITMQ_DEFAULT_USER: ${{ secrets.RABBITMQ_USER }}
      RABBITMQ_DEFAULT_PASS: ${{ secrets.RABBITMQ_PASSWORD }}
      TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
      ADMIN_ID: ${{ secrets.ADMIN_ID }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      REDIS_SSL: ${{ secrets.REDIS_SSL }}
      FIRST_SUPERUSER: ${{ secrets.FIRST_SUPERUSER }}
      FIRST_SUPERUSER_PASSWORD: ${{ secrets.FIRST_SUPERUSER_PASSWORD }}
      BACKEND_CORS_ORIGINS: ${{ secrets.BACKEND_CORS_ORIGINS }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
      REFRESH_TOKEN_EXPIRE_MINUTES: ${{ secrets.REFRESH_TOKEN_EXPIRE_MINUTES }}
      RABBITMQ_USER: ${{ secrets.RABBITMQ_USER }}
      RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}
      RABBITMQ_PORT: ${{ secrets.RABBITMQ_PORT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.8.22"
          enable-cache: true
        
      - name: Run tests
        run: uv run pytest
        working-directory: tgbot